### ISSUE TITLE
Crear mapeo de la base de datos

### ISSUE THREAD

**Issue by matirrudo** [DiegEstrada/TP_final_visual#2]
Realizar el mapeo a partir del modelo de base de datos.

**Comment by matirrudo** [comment]
Ya se terminaron todos los cambios en la base de datos  @IPATAGUA41 @fas23 @josericardo3396 @DiegEstrada 
Host: facultad.c0msve0brisr.us-east-2.rds.amazonaws.com
puerto: 3306
base de datos: heladeria
username: maestro
password: maestro1

**Comment by matirrudo** [comment]
Netbeans no responde al momento de crear el hibernate Mapping files and POJOs from database. Por favor alguno intente hacerlo por mi.

**Comment by josericardo3396** [comment]
Se realizo archivos de mapas de hibernate y pojos de la base de datos.
Luego ubicacion de las clases de dominio en sus respectivos paquetes.
